### ISSUE TITLE
error on variable substitution

### ISSUE THREAD

**Issue by COLABORATI** [sagarchalise/geanypy-emmet#5]
looks like some variable substitution does not work 100% - when I expand ```html:5``` I get 
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> ${17:Document}</title>
</head>
<body>
    
</body>
</html>
````
the ```${17:Document}``` should be only ```Document```

**Comment by sagarchalise** [comment]
I am currently closing this issue but havenot tested the latest commits. You may reopen this if something is wrong.
