### ISSUE TITLE
problem with utf-8 symbols

### ISSUE THREAD

**Issue by Proggggger** [sagarchalise/geanypy-emmet#6]
If my webpage contains for example cyrillic symbols emmet does not work
```
<body>
   <div class="wrapper">
      <div class="m">	Просто текст</div>
     <div id="tabaco">
    <div class="mm">	subst</div>
   </div>
   </div>
   
</body>
```
so Iprint for example .class but emmet does not do anything...

**Comment by sagarchalise** [comment]
This commit seems to fix the issue. I haven't thoroughly tested this. Do open the issue if any glitches.
